### signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "Djole1",
    "password": "djole1989/"
}

### signin
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "username": "Djole1",
    "password": "djole1989/"
}