
GET http://localhost:3000/reports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2YzMDM4NDdjZjc4MGEyMWJjZjAzOCIsInVzZXJuYW1lIjoiS3Jpc3RpbmEiLCJpYXQiOjE3NDg5NzE1ODIsImV4cCI6MTc0OTAwNzU4Mn0.TQ0TjP2DhkNFC5Z4Hf3y8ZhYdn5LFXn9e8JjhtaUp-U

### create report
POST http://localhost:3000/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2YzMDM4NDdjZjc4MGEyMWJjZjAzOCIsInVzZXJuYW1lIjoiS3Jpc3RpbmEiLCJpYXQiOjE3NDg5NzE1ODIsImV4cCI6MTc0OTAwNzU4Mn0.TQ0TjP2DhkNFC5Z4Hf3y8ZhYdn5LFXn9e8JjhtaUp-U

{
    "name": "Analize Report from 2001",
    "description": "Repote about animals"
}

### delete report
DELETE http://localhost:3000/reports/683474cdfbb0d6ff632bf73c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDcxNjU5NGFlZjVlYzZhNjVlZDE1NSIsInVzZXJuYW1lIjoiRGpvbGUxIiwiaWF0IjoxNzQ4MjY4MjYyLCJleHAiOjE3NDgzMDQyNjJ9.VU0lNHfOgokWEFoAIrpezRqqAkANQG9WA9N4VmOKe5A

### update report status
PATCH  http://localhost:3000/reports/683199bf372bf76ed41e0536/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzA4YjIzYmQxN2EwYTZmZWNkMzlhYyIsInVzZXJuYW1lIjoiS2lrYTEyMyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4NDQ2MDIyLCJleHAiOjE3NDg0ODIwMjJ9.jLC2uhPCgqO_2PC-xwLEMf_lGLSa8saP_NoF0nB26iw

{
    "status": "reviewing"
}

### create report comment
POST  http://localhost:3000/reports/683f302147cf780a21bcf035/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2YzMDM4NDdjZjc4MGEyMWJjZjAzOCIsInVzZXJuYW1lIjoiS3Jpc3RpbmEiLCJpYXQiOjE3NTA3NzQzNTIsImV4cCI6MTc1MDgxMDM1Mn0.xEVgsxm7gyFOgVnOmBB0YuKq_R_m619G6GzJ_rwIijU

{
    "message": "change the gif"
}

### get report comments
GET  http://localhost:3000/reports/683f302147cf780a21bcf035/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2YzMDM4NDdjZjc4MGEyMWJjZjAzOCIsInVzZXJuYW1lIjoiS3Jpc3RpbmEiLCJpYXQiOjE3NTA3NzQzNTIsImV4cCI6MTc1MDgxMDM1Mn0.xEVgsxm7gyFOgVnOmBB0YuKq_R_m619G6GzJ_rwIijU