### update
PUT http://localhost:3000/users/67d716594aef5ec6a65ed155
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRqb2xlMSIsImlhdCI6MTc0MjE0OTIxOSwiZXhwIjoxNzQyMTg1MjE5fQ.QlspMfnm-MwYR3vQUQTe7dpc1Yol5d8Kpv3N1lxFPAQ

{
    "mobile": "3asdddas6"
}