### get user
GET http://localhost:3000/users/678e491fb0f2ef47ad041a96

### signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "Krista",
    "password": "djole1989/"
}

### signin
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "username": "Krista",
    "password": "djole1989"
}

### update
PUT http://localhost:3000/users/678e491fb0f2ef47ad041a96
Content-Type: application/json

{
    "age": "32"
}